### ISSUE TITLE
Missing CSV IDs

### ISSUE THREAD

**Issue by RomashkaTea** [Gabriel55ita/BrawlDocs#3]
Missing csv IDs:

particle_emitters.csv: 10

color_gradients.csv: 46,
location_themes.csv: 47
game_mode_variations.csv: 48,
challenges.csv: 49

collabs.csv: 89

**Comment by RomashkaTea** [comment]
and.. new CSV IDs which added in v56:

class_archetypes.csv: 90
night_market_bundles.csv: 91
night_market_items.csv: 92

**Comment by Gabriel55ita** [comment]
Added all the new IDs 👍
